"""
GitHub integration for creating pull requests.
"""
import logging
from typing import Dict, Any
from github import Github, GithubException

logger = logging.getLogger(__name__)


class GitHubManager:
    """Manages GitHub operations like creating PRs."""

    def __init__(self, access_token: str):
        """Initialize GitHub client with access token."""
        self.client = Github(access_token)
        self.user = None

    def validate_token(self) -> bool:
        """Validate the GitHub access token."""
        try:
            self.user = self.client.get_user()
            logger.info(f"GitHub token validated for user: {self.user.login}")
            return True
        except GithubException as e:
            logger.error(f"Invalid GitHub token: {e}")
            return False

    async def create_pull_request(
        self,
        repo_url: str,
        file_path: str,
        code: str,
        commit_message: str,
        branch_name: str,
        pr_title: str,
        pr_body: str = ""
    ) -> Dict[str, Any]:
        """Create a pull request with the generated code."""
        try:
            repo_name = self._parse_repo_url(repo_url)
            repo = self.client.get_repo(repo_name)
            logger.info(f"Accessing repository: {repo_name}")

            default_branch = repo.default_branch
            source_branch = repo.get_branch(default_branch)

            logger.info(f"Creating branch: {branch_name}")
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=source_branch.commit.sha
            )

            logger.info(f"Creating/updating file: {file_path}")
            try:
                contents = repo.get_contents(file_path, ref=branch_name)
                repo.update_file(
                    path=file_path,
                    message=commit_message,
                    content=code,
                    sha=contents.sha,
                    branch=branch_name
                )
            except GithubException:
                repo.create_file(
                    path=file_path,
                    message=commit_message,
                    content=code,
                    branch=branch_name
                )

            logger.info(f"Creating pull request: {pr_title}")
            pr = repo.create_pull(
                title=pr_title,
                body=pr_body or f"Code generated by CodeAgent\n\n{commit_message}",
                head=branch_name,
                base=default_branch
            )

            logger.info(f"Pull request created: {pr.html_url}")

            return {
                "success": True,
                "pr_url": pr.html_url,
                "pr_number": pr.number,
                "branch": branch_name,
                "message": "Pull request created successfully!"
            }

        except GithubException as e:
            logger.error(f"GitHub API error: {e}", exc_info=True)
            return {
                "success": False,
                "error": f"GitHub error: {e.data.get('message', str(e)) if hasattr(e, 'data') else str(e)}"
            }
        except Exception as e:
            logger.error(f"Unexpected error: {e}", exc_info=True)
            return {
                "success": False,
                "error": f"Unexpected error: {str(e)}"
            }

    def _parse_repo_url(self, repo_url: str) -> str:
        """Parse repository URL to extract owner/repo format."""
        repo_url = repo_url.strip()

        if '/' in repo_url and 'github.com' not in repo_url:
            parts = repo_url.split('/')
            if len(parts) == 2:
                return repo_url
            raise ValueError(
                f"Invalid repository format: '{repo_url}'. "
                f"Expected format: 'username/repository' (e.g., 'itsprabhucbe/test-repo')"
            )

        if 'github.com' in repo_url:
            parts = repo_url.rstrip('/').split('/')
            if len(parts) >= 2:
                return f"{parts[-2]}/{parts[-1].replace('.git', '')}"

        raise ValueError(
            f"Invalid repository URL: '{repo_url}'. "
            f"Please use format: 'username/repository' (e.g., 'itsprabhucbe/test-repo')"
        )
