"use client";

import { useEffect, useState } from "react";

const LANGUAGES = ["python", "typescript", "javascript"] as const;
type Language = (typeof LANGUAGES)[number];

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

interface ExecuteResult {
  success: boolean;
  output: string | null;
  error: string | null;
  exit_code: number;
}

interface PRResult {
  success: boolean;
  pr_url?: string;
  pr_number?: number;
  branch?: string;
  message?: string;
  error?: string;
}

export default function Home() {
  const [task, setTask] = useState("");
  const [language, setLanguage] = useState<Language>("python");
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [executeResult, setExecuteResult] = useState<ExecuteResult | null>(null);
  const [executeLoading, setExecuteLoading] = useState(false);
  const [executeError, setExecuteError] = useState("");
  const [executionTime, setExecutionTime] = useState<number | null>(null);
  const [githubConnected, setGithubConnected] = useState(false);
  const [githubUser, setGithubUser] = useState<string | null>(null);
  const [sessionToken, setSessionToken] = useState<string | null>(null);
  const [showPRModal, setShowPRModal] = useState(false);
  const [repoUrl, setRepoUrl] = useState('');
  const [filePath, setFilePath] = useState('');
  const [commitMessage, setCommitMessage] = useState('');
  const [branchName, setBranchName] = useState('');
  const [prTitle, setPrTitle] = useState('');
  const [prCreating, setPrCreating] = useState(false);
  const [prResult, setPrResult] = useState<PRResult | null>(null);

  async function generate() {
    if (!task.trim() || loading) return;
    setLoading(true);
    setError("");
    setCode("");
    setExecuteResult(null);
    setExecuteError("");
    setExecutionTime(null);

    try {
      const res = await fetch(`${API_URL}/api/v1/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ task, language }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.detail ?? `Server error ${res.status}`);
      }

      const data = await res.json();
      setCode(data.code);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }

  async function handleExecute() {
    if (!code || executeLoading) return;
    setExecuteLoading(true);
    setExecuteError("");
    setExecuteResult(null);
    setExecutionTime(null);

    const start = Date.now();
    try {
      const res = await fetch(`${API_URL}/api/v1/execute`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code, language: "python" }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.detail ?? `Server error ${res.status}`);
      }

      const data: ExecuteResult = await res.json();
      setExecuteResult(data);
      setExecutionTime(Date.now() - start);
    } catch (err) {
      setExecuteError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setExecuteLoading(false);
    }
  }

  async function copyCode() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const handleConnectGitHub = () => {
    window.location.href = `${API_URL}/api/v1/auth/github`;
  };

  const handleDisconnectGitHub = () => {
    localStorage.removeItem('github_session_token');
    setSessionToken(null);
    setGithubConnected(false);
    setGithubUser(null);
  };

  const handleCreatePR = async () => {
    if (!sessionToken || !repoUrl || !filePath || !code) {
      alert('Please fill in all required fields');
      return;
    }

    setPrCreating(true);
    setPrResult(null);

    try {
      const branch = branchName || `codeagent-${Date.now()}`;

      const requestBody = {
        session_token: sessionToken,
        repo_url: repoUrl,
        file_path: filePath,
        code,
        commit_message: commitMessage || 'Add generated code from CodeAgent',
        branch_name: branch,
        pr_title: prTitle || 'Add generated code',
        pr_body: `Generated by CodeAgent 🤖\n\nTask: ${task}`
      };

      console.log('Creating PR with:', requestBody);

      const response = await fetch(`${API_URL}/api/v1/create-pr`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody)
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('PR creation failed:', response.status, errorText);
        throw new Error(`HTTP ${response.status}: ${errorText}`);
      }

      const data: PRResult = await response.json();
      setPrResult(data);

      if (data.success) {
        setRepoUrl('');
        setFilePath('');
        setCommitMessage('');
        setBranchName('');
        setPrTitle('');
      }
    } catch (error) {
      console.error('PR creation error:', error);
      setPrResult({
        success: false,
        error: error instanceof Error ? error.message : 'Failed to create PR. Check console for details.'
      });
    } finally {
      setPrCreating(false);
    }
  };

  useEffect(() => {
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === "Enter" && (e.metaKey || e.ctrlKey) && e.shiftKey && code) {
        e.preventDefault();
        handleExecute();
      }
    }
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [code, executeLoading]);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const connected = params.get('github_connected');
    const token = params.get('session_token');
    const user = params.get('github_user');

    if (connected === 'true' && token && user) {
      localStorage.setItem('github_session_token', token);
      setSessionToken(token);
      setGithubConnected(true);
      setGithubUser(user);
      window.history.replaceState({}, '', '/');
    }

    const savedToken = localStorage.getItem('github_session_token');
    if (savedToken) {
      setSessionToken(savedToken);
      fetch(`${API_URL}/api/v1/auth/github/status`, {
        headers: { 'Cookie': `session_token=${savedToken}` }
      })
        .then(res => res.json())
        .then(data => {
          if (data.connected) {
            setGithubConnected(true);
            setGithubUser(data.user);
          }
        })
        .catch(() => {});
    }
  }, []);

  return (
    <main className="max-w-3xl mx-auto px-4 py-16">
      {/* Header */}
      <div className="text-center mb-12">
        <h1 className="text-5xl font-bold tracking-tight mb-3">
          Code<span className="text-blue-400">Agent</span>
        </h1>
        <p className="text-gray-400 text-lg">
          Describe what you want to build — get working code instantly
        </p>
      </div>

      {/* GitHub connection */}
      <div className="mb-6 flex items-center justify-between bg-gray-800 rounded-lg p-4">
        {githubConnected ? (
          <>
            <div className="flex items-center gap-3">
              <svg className="w-6 h-6 text-green-400" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
              </svg>
              <div>
                <p className="text-sm text-gray-400">Connected as</p>
                <p className="font-semibold text-white">{githubUser}</p>
              </div>
            </div>
            <button
              onClick={handleDisconnectGitHub}
              className="px-4 py-2 text-sm bg-red-600 hover:bg-red-700 rounded transition-colors"
            >
              Disconnect
            </button>
          </>
        ) : (
          <>
            <p className="text-gray-400">Connect GitHub to create pull requests automatically</p>
            <button
              onClick={handleConnectGitHub}
              className="px-6 py-2 bg-gray-700 hover:bg-gray-600 rounded transition-colors flex items-center gap-2"
            >
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
              </svg>
              Connect GitHub
            </button>
          </>
        )}
      </div>

      {/* Input area */}
      <div className="space-y-3">
        <textarea
          className="w-full h-40 bg-gray-900 border border-gray-700 rounded-xl p-4 text-gray-100 placeholder-gray-500 focus:outline-none focus:border-blue-500 resize-none transition-colors font-mono text-sm"
          placeholder="e.g. Write a function that reverses a linked list in Python..."
          value={task}
          onChange={(e) => setTask(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) generate();
          }}
        />

        <div className="flex gap-3">
          <select
            className="bg-gray-900 border border-gray-700 rounded-lg px-4 py-2.5 text-gray-200 focus:outline-none focus:border-blue-500 transition-colors cursor-pointer"
            value={language}
            onChange={(e) => setLanguage(e.target.value as Language)}
          >
            {LANGUAGES.map((l) => (
              <option key={l} value={l}>
                {l.charAt(0).toUpperCase() + l.slice(1)}
              </option>
            ))}
          </select>

          <button
            onClick={generate}
            disabled={loading || !task.trim()}
            className="flex-1 bg-blue-600 hover:bg-blue-500 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed rounded-lg px-6 py-2.5 font-semibold transition-colors"
          >
            {loading ? (
              <span className="flex items-center justify-center gap-2">
                <span className="inline-block w-4 h-4 border-2 border-blue-300 border-t-transparent rounded-full animate-spin" />
                Generating...
              </span>
            ) : (
              "Generate  ⌘↵"
            )}
          </button>
        </div>
      </div>

      {/* Generate error */}
      {error && (
        <div className="mt-4 bg-red-950/60 border border-red-800 rounded-xl p-4 text-red-300 text-sm">
          {error}
        </div>
      )}

      {/* Generated code */}
      {code && (
        <div className="mt-6">
          <div className="flex items-center justify-between mb-2 px-1">
            <span className="text-xs text-gray-500 font-mono">{language}</span>
            <button
              onClick={copyCode}
              className="text-xs text-gray-400 hover:text-gray-200 bg-gray-800 hover:bg-gray-700 px-3 py-1 rounded-md transition-colors"
            >
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>
          <pre className="bg-gray-900 border border-gray-700 rounded-xl p-5 overflow-x-auto text-sm text-gray-100 font-mono leading-relaxed">
            <code>{code}</code>
          </pre>

          {/* Execute button */}
          <div className="mt-3 flex justify-end gap-3">
            <button
              onClick={handleExecute}
              disabled={executeLoading || !code}
              className="bg-green-700 hover:bg-green-600 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed rounded-lg px-6 py-2.5 font-semibold transition-colors text-sm"
            >
              {executeLoading ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="inline-block w-4 h-4 border-2 border-green-300 border-t-transparent rounded-full animate-spin" />
                  Executing...
                </span>
              ) : (
                "Execute Code  ⌘⇧↵"
              )}
            </button>
            {githubConnected && executeResult && executeResult.success && (
              <button
                onClick={() => setShowPRModal(true)}
                className="px-6 py-2.5 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors flex items-center gap-2 text-sm font-semibold"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4" />
                </svg>
                Create GitHub PR
              </button>
            )}
          </div>
        </div>
      )}

      {/* Execute error */}
      {executeError && (
        <div className="mt-4 bg-red-950/60 border border-red-800 rounded-xl p-4 text-red-300 text-sm">
          {executeError}
        </div>
      )}

      {/* Execution output panel */}
      {executeResult && (
        <div className="mt-4">
          <div className="flex items-center justify-between mb-2 px-1">
            <div className="flex items-center gap-2">
              <span
                className={`inline-block w-2 h-2 rounded-full ${
                  executeResult.success ? "bg-green-400" : "bg-red-400"
                }`}
              />
              <span
                className={`text-xs font-semibold ${
                  executeResult.success ? "text-green-400" : "text-red-400"
                }`}
              >
                {executeResult.success
                  ? "Success"
                  : `Failed (exit ${executeResult.exit_code})`}
              </span>
            </div>
            {executionTime !== null && (
              <span className="text-xs text-gray-500 font-mono">{executionTime}ms</span>
            )}
          </div>
          <div className="bg-gray-900 border border-gray-700 rounded-xl p-5 font-mono text-sm leading-relaxed space-y-3">
            {executeResult.output && (
              <div>
                <span className="text-xs text-gray-500 block mb-1">stdout</span>
                <pre className="text-gray-100 whitespace-pre-wrap">{executeResult.output}</pre>
              </div>
            )}
            {executeResult.error && (
              <div>
                <span className="text-xs text-gray-500 block mb-1">stderr</span>
                <pre className="text-red-300 whitespace-pre-wrap">{executeResult.error}</pre>
              </div>
            )}
            {!executeResult.output && !executeResult.error && (
              <span className="text-gray-500">(no output)</span>
            )}
          </div>
        </div>
      )}
      {/* PR creation modal */}
      {showPRModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-gray-800 rounded-lg p-6 max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
            <h2 className="text-2xl font-bold mb-4">Create GitHub Pull Request</h2>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-2">Repository *</label>
                <input
                  type="text"
                  value={repoUrl}
                  onChange={(e) => setRepoUrl(e.target.value)}
                  placeholder="username/repo"
                  className="w-full px-4 py-2 bg-gray-700 rounded border border-gray-600 focus:border-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">File Path *</label>
                <input
                  type="text"
                  value={filePath}
                  onChange={(e) => setFilePath(e.target.value)}
                  placeholder="src/utils.py"
                  className="w-full px-4 py-2 bg-gray-700 rounded border border-gray-600 focus:border-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">Commit Message</label>
                <input
                  type="text"
                  value={commitMessage}
                  onChange={(e) => setCommitMessage(e.target.value)}
                  placeholder="Add generated code from CodeAgent"
                  className="w-full px-4 py-2 bg-gray-700 rounded border border-gray-600 focus:border-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">Branch Name (optional)</label>
                <input
                  type="text"
                  value={branchName}
                  onChange={(e) => setBranchName(e.target.value)}
                  placeholder="Auto-generated if empty"
                  className="w-full px-4 py-2 bg-gray-700 rounded border border-gray-600 focus:border-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">PR Title</label>
                <input
                  type="text"
                  value={prTitle}
                  onChange={(e) => setPrTitle(e.target.value)}
                  placeholder="Add generated code"
                  className="w-full px-4 py-2 bg-gray-700 rounded border border-gray-600 focus:border-blue-500 outline-none"
                />
              </div>

              {prResult && (
                <div className={`p-4 rounded ${prResult.success ? 'bg-green-900 border border-green-700' : 'bg-red-900 border border-red-700'}`}>
                  {prResult.success ? (
                    <div>
                      <p className="font-medium text-green-100">Pull Request Created!</p>
                      <a
                        href={prResult.pr_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-green-300 hover:text-green-200 underline mt-2 inline-block"
                      >
                        View PR #{prResult.pr_number} →
                      </a>
                    </div>
                  ) : (
                    <p className="text-red-100">{prResult.error}</p>
                  )}
                </div>
              )}
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={handleCreatePR}
                disabled={prCreating || !repoUrl || !filePath}
                className="flex-1 px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors disabled:opacity-50"
              >
                {prCreating ? 'Creating PR...' : 'Create Pull Request'}
              </button>
              <button
                onClick={() => {
                  setShowPRModal(false);
                  setPrResult(null);
                }}
                className="px-6 py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}
